# server/ml-service/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_lg

COPY . .

CMD ["uvicorn", "src.api.routes:app", "--host", "0.0.0.0", "--port", "8000"]